[build]
  publish = "build/"
  command = "yarn build"

[context.master.environment]
  REACT_APP_MAIN_API_URL = "https://webrtc-server-x4rsj.ondigitalocean.app/webrtc"
  REACT_APP_PEER_URL = ""
  REACT_APP_PEER_PORT = ""

[context.develop.environment]
  REACT_APP_MAIN_API_URL = "https://webrtc-server-x4rsj.ondigitalocean.app/webrtc"
  REACT_APP_PEER_URL = ""
  REACT_APP_PEER_PORT = ""

# The following redirect is intended for use with most SPAs that handle
# routing internally.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
